toggle console output button in settings
makscee/arena-of-ideas pull request #201
Opened 2024-05-03 03:37 UTC by kannerry

when this setting is toggled on it will turn off console logging and that makes the game process faster

https://youtu.be/8Y8_-6dvtL0

2024-05-10 12:38 UTC, makscee requested changes

2024-05-10 12:38 UTC, makscee commented on src/plugins/settings.rs
> +                            "disable console output".to_colored().label(&mut ui[0]);
Since buttons say "enabled"/"disabled" option should be called just "console output"

2024-05-10 12:38 UTC, makscee commented on src/plugins/settings.rs
> +                if data.dev_mode {
This will make it so console output is enabled by default, and to disable it we have to enable dev mode first.
We can just always show this option

2024-05-10 12:38 UTC, makscee commented on src/plugins/settings.rs
> +                                if *value == false {
replace with 
```rust
if *value {

} else {

}
```

2024-05-12 14:58 UTC, kannerry commented
should be good now

2024-05-13 10:44 UTC, makscee approved these changes

2024-05-13 10:45 UTC, merged